//
//  StubData.swift
//  NetworkTests
//
//  Created by 강민수 on 2023/04/18.
//

import UIKit

struct StubData {
    
    static let imageData: Data = UIImage(named: "star")!.pngData()!
    static let matchData: Data = """
{
        "matchId": "63f18d93e982f639cfe3822c",
        "matchDate": "2023-02-19T11:56:59",
        "matchType": 50,
        "matchInfo": [
                {
                        "accessId": "68bb3f88b9b7e862a2639a9d",
                        "nickname": "민수쨔응",
                        "matchDetail": {
                                "seasonId": 202302,
                                "matchResult": "패",
                                "matchEndType": 0,
                                "systemPause": 0,
                                "foul": 0,
                                "injury": 0,
                                "redCards": 0,
                                "yellowCards": 0,
                                "dribble": 93,
                                "cornerKick": 0,
                                "possession": 53,
                                "offsideCount": 1,
                                "averageRating": 3.91667,
                                "controller": "keyboard"
                        },
                        "shoot": {
                                "shootTotal": 2,
                                "effectiveShootTotal": 1,
                                "shootOutScore": 0,
                                "goalTotal": 1,
                                "goalTotalDisplay": 1,
                                "ownGoal": 0,
                                "shootHeading": 0,
                                "goalHeading": 0,
                                "shootFreekick": 0,
                                "goalFreekick": 0,
                                "shootInPenalty": 1,
                                "goalInPenalty": 1,
                                "shootOutPenalty": 1,
                                "goalOutPenalty": 0,
                                "shootPenaltyKick": 0,
                                "goalPenaltyKick": 0
                        },
                        "shootDetail": [
                                {
                                        "goalTime": 16778027,
                                        "x": 0.8945176601409912,
                                        "y": 0.5372314453125,
                                        "type": 2,
                                        "result": 3,
                                        "spId": 260204485,
                                        "spGrade": 3,
                                        "spLevel": 5,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 242239085,
                                        "assistX": 0.8272744417190552,
                                        "assistY": 0.464475691318512,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 16778828,
                                        "x": 0.8337321877479553,
                                        "y": 0.6191255450248718,
                                        "type": 2,
                                        "result": 2,
                                        "spId": 242239085,
                                        "spGrade": 5,
                                        "spLevel": 5,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 260192985,
                                        "assistX": 0.6241644620895386,
                                        "assistY": 0.5713242888450623,
                                        "hitPost": false,
                                        "inPenalty": false
                                }
                        ],
                        "pass": {
                                "passTry": 131,
                                "passSuccess": 118,
                                "shortPassTry": 101,
                                "shortPassSuccess": 95,
                                "longPassTry": 2,
                                "longPassSuccess": 1,
                                "bouncingLobPassTry": 0,
                                "bouncingLobPassSuccess": 0,
                                "drivenGroundPassTry": 0,
                                "drivenGroundPassSuccess": 0,
                                "throughPassTry": 26,
                                "throughPassSuccess": 22,
                                "lobbedThroughPassTry": 0,
                                "lobbedThroughPassSuccess": 0
                        },
                        "defence": {
                                "blockTry": 13,
                                "blockSuccess": 1,
                                "tackleTry": 2,
                                "tackleSuccess": 2
                        },
                        "player": [
                                {
                                        "spId": 242237692,
                                        "spPosition": 27,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 11,
                                                "passSuccess": 9,
                                                "dribbleTry": 14,
                                                "dribbleSuccess": 10,
                                                "ballPossesionTry": 6,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 1,
                                                "aerialSuccess": 0,
                                                "blockTry": 1,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 5.8
                                        }
                                },
                                {
                                        "spId": 279231866,
                                        "spPosition": 9,
                                        "spGrade": 4,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 12,
                                                "passSuccess": 11,
                                                "dribbleTry": 9,
                                                "dribbleSuccess": 9,
                                                "ballPossesionTry": 3,
                                                "ballPossesionSuccess": 2,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 6
                                        }
                                },
                                {
                                        "spId": 249020289,
                                        "spPosition": 14,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 1,
                                                "defending": 0,
                                                "passTry": 19,
                                                "passSuccess": 18,
                                                "dribbleTry": 17,
                                                "dribbleSuccess": 15,
                                                "ballPossesionTry": 4,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 1,
                                                "aerialSuccess": 0,
                                                "blockTry": 2,
                                                "block": 0,
                                                "tackleTry": 1,
                                                "tackle": 1,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 6.9
                                        }
                                },
                                {
                                        "spId": 233168542,
                                        "spPosition": 28,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 260188377,
                                        "spPosition": 11,
                                        "spGrade": 3,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 17,
                                                "passSuccess": 16,
                                                "dribbleTry": 13,
                                                "dribbleSuccess": 12,
                                                "ballPossesionTry": 3,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 1,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 6.3
                                        }
                                },
                                {
                                        "spId": 206191043,
                                        "spPosition": 28,
                                        "spGrade": 2,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 260192985,
                                        "spPosition": 18,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 17,
                                                "passSuccess": 14,
                                                "dribbleTry": 12,
                                                "dribbleSuccess": 12,
                                                "ballPossesionTry": 4,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 6.2
                                        }
                                },
                                {
                                        "spId": 318199258,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 242203574,
                                        "spPosition": 4,
                                        "spGrade": 8,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 4,
                                                "passSuccess": 4,
                                                "dribbleTry": 2,
                                                "dribbleSuccess": 2,
                                                "ballPossesionTry": 1,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 5.5
                                        }
                                },
                                {
                                        "spId": 260204485,
                                        "spPosition": 23,
                                        "spGrade": 3,
                                        "status": {
                                                "shoot": 1,
                                                "effectiveShoot": 1,
                                                "assist": 0,
                                                "goal": 1,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 11,
                                                "passSuccess": 11,
                                                "dribbleTry": 10,
                                                "dribbleSuccess": 8,
                                                "ballPossesionTry": 3,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 7.1
                                        }
                                },
                                {
                                        "spId": 300209423,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 508210257,
                                        "spPosition": 0,
                                        "spGrade": 6,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 11,
                                                "passTry": 13,
                                                "passSuccess": 11,
                                                "dribbleTry": 1,
                                                "dribbleSuccess": 1,
                                                "ballPossesionTry": 8,
                                                "ballPossesionSuccess": 6,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 9.2
                                        }
                                },
                                {
                                        "spId": 273212218,
                                        "spPosition": 6,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 7,
                                                "passSuccess": 5,
                                                "dribbleTry": 3,
                                                "dribbleSuccess": 3,
                                                "ballPossesionTry": 3,
                                                "ballPossesionSuccess": 3,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 2,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 4.4
                                        }
                                },
                                {
                                        "spId": 511215604,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 253229237,
                                        "spPosition": 5,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 2,
                                                "defending": 0,
                                                "passTry": 4,
                                                "passSuccess": 4,
                                                "dribbleTry": 1,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 2,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 7,
                                                "block": 1,
                                                "tackleTry": 1,
                                                "tackle": 1,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 5.5
                                        }
                                },
                                {
                                        "spId": 260239818,
                                        "spPosition": 28,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 300253163,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 242239085,
                                        "spPosition": 25,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 1,
                                                "effectiveShoot": 0,
                                                "assist": 1,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 16,
                                                "passSuccess": 15,
                                                "dribbleTry": 11,
                                                "dribbleSuccess": 11,
                                                "ballPossesionTry": 2,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 1,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 7.6
                                        }
                                }
                        ]
                },
                {
                        "accessId": "7da5c1eb63432f5eb215ab58",
                        "nickname": "또트트릭홀란드",
                        "matchDetail": {
                                "seasonId": 202302,
                                "matchResult": "승",
                                "matchEndType": 0,
                                "systemPause": 0,
                                "foul": 0,
                                "injury": 0,
                                "redCards": 0,
                                "yellowCards": 0,
                                "dribble": 70,
                                "cornerKick": 5,
                                "possession": 47,
                                "offsideCount": 1,
                                "averageRating": 4.29444,
                                "controller": "keyboard"
                        },
                        "shoot": {
                                "shootTotal": 14,
                                "effectiveShootTotal": 9,
                                "shootOutScore": 0,
                                "goalTotal": 2,
                                "goalTotalDisplay": 2,
                                "ownGoal": 0,
                                "shootHeading": 4,
                                "goalHeading": 1,
                                "shootFreekick": 0,
                                "goalFreekick": 0,
                                "shootInPenalty": 9,
                                "goalInPenalty": 2,
                                "shootOutPenalty": 5,
                                "goalOutPenalty": 0,
                                "shootPenaltyKick": 0,
                                "goalPenaltyKick": 0
                        },
                        "shootDetail": [
                                {
                                        "goalTime": 2486,
                                        "x": 0.9262362718582152,
                                        "y": 0.3451355695724487,
                                        "type": 1,
                                        "result": 1,
                                        "spId": 234020801,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": false,
                                        "assistSpId": -1,
                                        "assistX": 0.5,
                                        "assistY": 0.5,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 2541,
                                        "x": 0.934428870677948,
                                        "y": 0.4451488256454468,
                                        "type": 3,
                                        "result": 2,
                                        "spId": 234020801,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": false,
                                        "assistSpId": -1,
                                        "assistX": 0.5,
                                        "assistY": 0.5,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 2621,
                                        "x": 0.9116384983062744,
                                        "y": 0.4421389997005463,
                                        "type": 3,
                                        "result": 3,
                                        "spId": 237165153,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 234183277,
                                        "assistX": 0.8995460271835327,
                                        "assistY": 0.1536840051412582,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 2788,
                                        "x": 0.7939339876174927,
                                        "y": 0.5272365212440491,
                                        "type": 1,
                                        "result": 1,
                                        "spId": 234020801,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 237165153,
                                        "assistX": 0.5716410875320435,
                                        "assistY": 0.5332545638084412,
                                        "hitPost": false,
                                        "inPenalty": false
                                },
                                {
                                        "goalTime": 16778989,
                                        "x": 0.808090090751648,
                                        "y": 0.4263162314891815,
                                        "type": 1,
                                        "result": 2,
                                        "spId": 237165153,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 234020801,
                                        "assistX": 0.5419094562530518,
                                        "assistY": 0.5721907615661621,
                                        "hitPost": true,
                                        "inPenalty": false
                                },
                                {
                                        "goalTime": 16779351,
                                        "x": 0.8532736897468567,
                                        "y": 0.519394040107727,
                                        "type": 1,
                                        "result": 1,
                                        "spId": 237165153,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 234020801,
                                        "assistX": 0.7507817149162292,
                                        "assistY": 0.5758492946624756,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 16779497,
                                        "x": 0.80891877412796,
                                        "y": 0.5602952241897583,
                                        "type": 2,
                                        "result": 1,
                                        "spId": 234183277,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 234214100,
                                        "assistX": 0.8498548865318298,
                                        "assistY": 0.9467921257019044,
                                        "hitPost": false,
                                        "inPenalty": false
                                },
                                {
                                        "goalTime": 16779762,
                                        "x": 0.805052638053894,
                                        "y": 0.5951176881790161,
                                        "type": 1,
                                        "result": 1,
                                        "spId": 234214100,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 272189505,
                                        "assistX": 0.9095443487167358,
                                        "assistY": 0.7614628672599792,
                                        "hitPost": false,
                                        "inPenalty": false
                                },
                                {
                                        "goalTime": 16780035,
                                        "x": 0.8885822892189026,
                                        "y": 0.5200668573379517,
                                        "type": 1,
                                        "result": 2,
                                        "spId": 260229984,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": false,
                                        "assistSpId": -1,
                                        "assistX": 0.5,
                                        "assistY": 0.5,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 245,
                                        "x": 0.89482969045639,
                                        "y": 0.4915271699428558,
                                        "type": 1,
                                        "result": 1,
                                        "spId": 234020801,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 234183277,
                                        "assistX": 0.8384218215942383,
                                        "assistY": 0.5578940510749817,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 593,
                                        "x": 0.9140905737876892,
                                        "y": 0.5304989218711853,
                                        "type": 3,
                                        "result": 2,
                                        "spId": 237165153,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": false,
                                        "assistSpId": -1,
                                        "assistX": 0.5,
                                        "assistY": 0.5,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 948,
                                        "x": 0.8397192955017,
                                        "y": 0.5468783378601074,
                                        "type": 1,
                                        "result": 1,
                                        "spId": 234183277,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 272189505,
                                        "assistX": 0.662380039691925,
                                        "assistY": 0.5686417818069458,
                                        "hitPost": false,
                                        "inPenalty": false
                                },
                                {
                                        "goalTime": 1679,
                                        "x": 0.9044159054756165,
                                        "y": 0.556099534034729,
                                        "type": 1,
                                        "result": 3,
                                        "spId": 234020801,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 237165153,
                                        "assistX": 0.551653265953064,
                                        "assistY": 0.6057683229446411,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 1870,
                                        "x": 0.8672770261764526,
                                        "y": 0.5896621346473694,
                                        "type": 1,
                                        "result": 1,
                                        "spId": 234020801,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 234003647,
                                        "assistX": 0.5990852117538452,
                                        "assistY": 0.5879896879196167,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 1932,
                                        "x": 0.9365845322608948,
                                        "y": 0.3620224595069885,
                                        "type": 3,
                                        "result": 2,
                                        "spId": 234020801,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": true,
                                        "assistSpId": 234003647,
                                        "assistX": 0.5990852117538452,
                                        "assistY": 0.5879896879196167,
                                        "hitPost": false,
                                        "inPenalty": true
                                },
                                {
                                        "goalTime": 2858,
                                        "x": 0.8955481648445129,
                                        "y": 0.5928280353546143,
                                        "type": 3,
                                        "result": 2,
                                        "spId": 265232756,
                                        "spGrade": 5,
                                        "spLevel": 4,
                                        "spIdType": true,
                                        "assist": false,
                                        "assistSpId": -1,
                                        "assistX": 0.5,
                                        "assistY": 0.5,
                                        "hitPost": false,
                                        "inPenalty": true
                                }
                        ],
                        "pass": {
                                "passTry": 87,
                                "passSuccess": 78,
                                "shortPassTry": 19,
                                "shortPassSuccess": 19,
                                "longPassTry": 9,
                                "longPassSuccess": 5,
                                "bouncingLobPassTry": 0,
                                "bouncingLobPassSuccess": 0,
                                "drivenGroundPassTry": 0,
                                "drivenGroundPassSuccess": 0,
                                "throughPassTry": 59,
                                "throughPassSuccess": 54,
                                "lobbedThroughPassTry": 0,
                                "lobbedThroughPassSuccess": 0
                        },
                        "defence": {
                                "blockTry": 6,
                                "blockSuccess": 0,
                                "tackleTry": 12,
                                "tackleSuccess": 8
                        },
                        "player": [
                                {
                                        "spId": 234020801,
                                        "spPosition": 25,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 6,
                                                "effectiveShoot": 4,
                                                "assist": 0,
                                                "goal": 1,
                                                "dribble": 7,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 5,
                                                "passSuccess": 5,
                                                "dribbleTry": 11,
                                                "dribbleSuccess": 7,
                                                "ballPossesionTry": 6,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 3,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 7.9
                                        }
                                },
                                {
                                        "spId": 234214100,
                                        "spPosition": 9,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 1,
                                                "effectiveShoot": 1,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 1,
                                                "defending": 0,
                                                "passTry": 15,
                                                "passSuccess": 13,
                                                "dribbleTry": 6,
                                                "dribbleSuccess": 6,
                                                "ballPossesionTry": 4,
                                                "ballPossesionSuccess": 2,
                                                "aerialTry": 1,
                                                "aerialSuccess": 0,
                                                "blockTry": 1,
                                                "block": 0,
                                                "tackleTry": 2,
                                                "tackle": 1,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 7.4
                                        }
                                },
                                {
                                        "spId": 260235212,
                                        "spPosition": 2,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 1,
                                                "defending": 0,
                                                "passTry": 8,
                                                "passSuccess": 6,
                                                "dribbleTry": 8,
                                                "dribbleSuccess": 7,
                                                "ballPossesionTry": 5,
                                                "ballPossesionSuccess": 3,
                                                "aerialTry": 1,
                                                "aerialSuccess": 1,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 2,
                                                "tackle": 1,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 6.9
                                        }
                                },
                                {
                                        "spId": 300238287,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 300242512,
                                        "spPosition": 28,
                                        "spGrade": 2,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 300245391,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 234003647,
                                        "spPosition": 11,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 9,
                                                "passSuccess": 9,
                                                "dribbleTry": 5,
                                                "dribbleSuccess": 5,
                                                "ballPossesionTry": 1,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 6.4
                                        }
                                },
                                {
                                        "spId": 237165153,
                                        "spPosition": 18,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 3,
                                                "effectiveShoot": 2,
                                                "assist": 1,
                                                "goal": 1,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 14,
                                                "passSuccess": 11,
                                                "dribbleTry": 10,
                                                "dribbleSuccess": 9,
                                                "ballPossesionTry": 8,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 3,
                                                "aerialSuccess": 1,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 1,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 8.1
                                        }
                                },
                                {
                                        "spId": 234183277,
                                        "spPosition": 16,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 2,
                                                "effectiveShoot": 2,
                                                "assist": 1,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 10,
                                                "passSuccess": 9,
                                                "dribbleTry": 10,
                                                "dribbleSuccess": 10,
                                                "ballPossesionTry": 3,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 8.2
                                        }
                                },
                                {
                                        "spId": 272189505,
                                        "spPosition": 23,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 1,
                                                "defending": 0,
                                                "passTry": 10,
                                                "passSuccess": 9,
                                                "dribbleTry": 10,
                                                "dribbleSuccess": 8,
                                                "ballPossesionTry": 7,
                                                "ballPossesionSuccess": 4,
                                                "aerialTry": 1,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 1,
                                                "tackle": 1,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 7.6
                                        }
                                },
                                {
                                        "spId": 234192119,
                                        "spPosition": 0,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 2,
                                                "passSuccess": 2,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 5.4
                                        }
                                },
                                {
                                        "spId": 300193098,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 253201535,
                                        "spPosition": 4,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 4,
                                                "defending": 0,
                                                "passTry": 9,
                                                "passSuccess": 9,
                                                "dribbleTry": 6,
                                                "dribbleSuccess": 6,
                                                "ballPossesionTry": 5,
                                                "ballPossesionSuccess": 5,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 4,
                                                "tackle": 4,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 7.5
                                        }
                                },
                                {
                                        "spId": 260229984,
                                        "spPosition": 8,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 1,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 2,
                                                "passSuccess": 2,
                                                "dribbleTry": 2,
                                                "dribbleSuccess": 2,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 3,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 5.8
                                        }
                                },
                                {
                                        "spId": 265232756,
                                        "spPosition": 6,
                                        "spGrade": 5,
                                        "status": {
                                                "shoot": 1,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 1,
                                                "defending": 0,
                                                "passTry": 3,
                                                "passSuccess": 3,
                                                "dribbleTry": 2,
                                                "dribbleSuccess": 2,
                                                "ballPossesionTry": 2,
                                                "ballPossesionSuccess": 1,
                                                "aerialTry": 2,
                                                "aerialSuccess": 1,
                                                "blockTry": 2,
                                                "block": 0,
                                                "tackleTry": 2,
                                                "tackle": 1,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 6.1
                                        }
                                },
                                {
                                        "spId": 300247686,
                                        "spPosition": 28,
                                        "spGrade": 3,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 321248694,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                },
                                {
                                        "spId": 300268438,
                                        "spPosition": 28,
                                        "spGrade": 1,
                                        "status": {
                                                "shoot": 0,
                                                "effectiveShoot": 0,
                                                "assist": 0,
                                                "goal": 0,
                                                "dribble": 0,
                                                "intercept": 0,
                                                "defending": 0,
                                                "passTry": 0,
                                                "passSuccess": 0,
                                                "dribbleTry": 0,
                                                "dribbleSuccess": 0,
                                                "ballPossesionTry": 0,
                                                "ballPossesionSuccess": 0,
                                                "aerialTry": 0,
                                                "aerialSuccess": 0,
                                                "blockTry": 0,
                                                "block": 0,
                                                "tackleTry": 0,
                                                "tackle": 0,
                                                "yellowCards": 0,
                                                "redCards": 0,
                                                "spRating": 0
                                        }
                                }
                        ]
                }
        ]
}
""".data(using: .utf8)!
}
